# Generated by Django 4.2.1 on 2023-06-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('released_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_expired', models.BooleanField(default=False)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
