# Generated by Django 4.2.1 on 2023-07-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='offer',
        ),
    ]
