# Generated by Django 4.2.1 on 2023-07-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='save_info',
            field=models.BooleanField(default=True),
        ),
    ]
