# Generated by Django 4.2.1 on 2023-06-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodetails',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
