# Generated by Django 4.2.1 on 2023-06-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_product_prodetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodetails',
            field=models.CharField(default='Full des', max_length=250),
        ),
    ]
