# Generated by Django 4.2.1 on 2023-06-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
