# Generated by Django 4.2.1 on 2023-06-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image1',
            field=models.ImageField(null=True, upload_to='photos/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(null=True, upload_to='photos/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(null=True, upload_to='photos/product'),
        ),
    ]
