# Generated by Django 4.2.1 on 2023-07-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_alter_coupon_discount'),
        ('cartapp', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon.offer'),
        ),
    ]
