# Generated by Django 4.2.1 on 2023-07-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
